---
title: "Lobsters"
author: "Amritpal Sandhu"
date: "2022-08-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(here)
```


```{r}
lobsters <- read_csv(here::here("data", "Lobster_Abundance_All_Years_20210412.csv"), na = c("-99999", " ")) |> 
  clean_names() |>
  uncount(count)
  
```

```{r}
# Find total counts and mean carpace lengths by site and year

lobster_summary <- lobsters |>
  group_by(site, year) |> 
  summarize(total_counts = n(),
            carpace_length = mean(size_mm, na.rm =TRUE))

ggplot(data = lobster_summary, aes (x = year, y = total_counts, group = site)) + geom_point() + labs(x = "Year", y = "Total Count of Lobsters")
```

```{r}
lobster_subset <- lobsters |> filter(year == 2020)

lobster_count <- lobster_subset|> 
  mutate(legal = ifelse(size_mm > 79.76, yes = "yes", no = "no")) |>
  group_by(site, legal) |>
  summarize(count = n())

ggplot(data = lobster_count, aes(x = site, y = count)) + geom_col(position = "fill", 
        aes(fill = legal)) 
```

## Task 3

```{r}
ex_a <- lobsters |> 
  filter(site == "IVEE" | site == "CARP" | site == "NAPL")

# or ex_a <- lobsters |> filter(site == c("IVEE", "CARP", "NAPL")

ex_b <- lobsters |>
  filter(month == "8")

ex_c <- lobsters |> 
  filter(site == "AQUE" | size_mm > 70)

ex_d <- lobsters |>
  filter(site != 'NAPL')

ex_e <- lobsters |>
  group_by(site) |> 
  summarize(mean_length = mean(size_mm, na.rm = TRUE),
           sd_length = sd(size_mm, na.rm = TRUE))

ex_f <- lobsters |>
  group_by(site, month) |>
  summarize(max_length = max(size_mm, na.rm = TRUE))
           
ex_g <- lobsters |>
  mutate (carpace_length_cm = size_mm / 10)

ex_h <- lobsters |>
  clean_names()

ex_i <- lobsters |>
  mutate(area = as.character(area))

ex_j <- lobsters |> 
  mutate(
    size_bin = case_when(size_mm <= 70 ~ "small",
                         size_mm > 70 ~ "large"))
 
# ex_k <- lobsters |> mutate(designation = if (site = "IVEE") {print (paste0("MPA"))} else if (site = "NAPL") {print(paste0("MPA"))})
                          

```

